---
- name: Add nvm to bash
  lineinfile:
    dest: "/home/{{ vireo_user }}/.bashrc"
    line: cd ~
    insertafter: EOF

- name: Install nvm for user {{ vireo_user }}
  shell: "curl -o- https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh | bash"
  become: true
  become_user: "{{ vireo_user }}"
  args:
    warn: false

#- name: Add nvm to bash
#  lineinfile:
#    dest: "/home/{{ vireo_user }}/.bashrc"
#    line: source ~/.nvm/nvm.sh
#    insertafter: EOF

- name: Install nodejs for user {{ vireo_user }}
  shell: source /home/{{ vireo_user }}/.bashrc && nvm install v{{ node_version }}
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ vireo_user }}"

- name: Install nyc for user {{ vireo_user }}
  shell: source /home/{{ vireo_user }}/.bashrc && npm i -D nyc
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ vireo_user }}"

- name: Install yarn for user {{ vireo_user }}
  shell: source /home/{{ vireo_user }}/.bashrc && npm install -g yarn
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ vireo_user }}"

- name: Install grunt-cli for user {{ vireo_user }}
  shell: source /home/{{ vireo_user }}/.bashrc && npm install -g grunt-cli
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ vireo_user }}"


